import json
import os
import base64
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from openai import OpenAI

# This script post-processes the JSON produced by Extract.py.
# It walks over all SKUs and their associated images and calls a
# placeholder function `classify_image_with_gpt` for each image.
#
# You must implement the actual GPT (or other vision model) call
# inside `classify_image_with_gpt` using your preferred client
# library and API key. The rest of the script focuses on:
# - loading the latest analysis JSON
# - iterating over image paths
# - enriching the JSON with hardware-tool classifications
# - writing a new versioned JSON file next to the original

PROJECT_ROOT = Path(__file__).parent
OUTPUT_DIR = PROJECT_ROOT / "output"

_openai_client: Optional[OpenAI] = None


def _get_openai_client() -> OpenAI:
    """Lazily instantiate and cache the OpenAI client.

    Expects OPENAI_API_KEY to be set in the environment.
    """
    global _openai_client
    if _openai_client is None:
        _openai_client = OpenAI()
    return _openai_client


def find_latest_analysis_json() -> Optional[Path]:
    """Return the newest *_analysis_v*.json file in OUTPUT_DIR, if any."""
    if not OUTPUT_DIR.exists():
        return None

    candidates: List[Path] = []
    for p in OUTPUT_DIR.iterdir():
        if p.is_file() and p.name.endswith(".json") and "_analysis_v" in p.name:
            candidates.append(p)

    if not candidates:
        return None

    # Sort by modification time, newest first
    candidates.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return candidates[0]


def classify_image_with_gpt(image_path: Path) -> Tuple[bool, List[str], Optional[float]]:
    """Classify a single image using a vision-capable GPT model.

    This is the **second step** in the two-step image filter:

    1. Extract.py has already:
       - filtered out very small images (likely icons / logos) by area
       - aligned images to SKUs per table / page.
    2. This function now decides whether the remaining image is an
       *actual product image* (hardware tool / pipe / tube, etc.).

    The typical visual pattern in these catalogs is:
    - A physical object (tool, hardware part, pipe, tube, fitting, etc.)
      shown in color.
    - The object is placed on a white page background (PDF paper), so
      the outer border of the image is mostly white.
    - All non-white parts inside that border are considered part of the
      product image (e.g. metal grey, black, blue, gold, etc.).

    Your vision model should:
    - Return **True** for real products (e.g. compressor, wrench,
      coupling, valve, pipe section, hose, connector, etc.).
    - Return **False** for pure logos, icons, schematic arrows,
      decorative graphics, or blank areas, even if they are on white.

    Parameters
    ----------
    image_path: Path
        Local path to the image file (e.g. WEBP) generated by Extract.py.

    Returns
    -------
    is_hardware_tool: bool
        True if the image is considered to show a hardware tool /
        hardware part / pipe / tube (i.e. a physical product).
    labels: List[str]
        List of labels for the tools detected, for example
        ["hammer", "screwdriver", "pipe", "valve"]. Can be empty.
    confidence: Optional[float]
        Optional confidence score in [0, 1]. Can be None if your
        model/client does not provide it.

    Implementation guideline (to be filled in by you):
    - Open the image in binary mode.
    - Send it to a multimodal / vision GPT model with a prompt along
      these lines (in natural language, not literally including
      quotes inside the prompt string):

        You see a product image from a hardware / tools / pipes catalog.
        The product is typically in color (e.g. metal grey, black, blue,
        gold) and placed on a white page background. Treat the outer
        white area as paper/background, and everything non-white inside
        the border as part of the product.

        Decide if this is an actual physical product such as a tool,
        hardware component, pipe, tube, fitting, hose, coupling,
        compressor, pump, or similar item.

        Ignore and classify as not-a-product if the image is mainly a
        logo, a simple icon or symbol, a purely decorative graphic, or
        an empty/almost empty area.

        Respond ONLY as strict JSON with keys:
        - is_hardware_tool: boolean
        - labels: array of short product type strings (e.g. ["pipe",
          "valve"])
        - confidence: number between 0 and 1

    - Parse the JSON response from the model and map it to the
      (is_hardware_tool, labels, confidence) tuple.

    This function is intentionally left as a stub so you can plug in
    your specific API client (OpenAI, Azure, etc.) and model name.
    """
    client = _get_openai_client()

    try:
        with image_path.open("rb") as f:
            image_bytes = f.read()
    except Exception:
        # If the image cannot be read, treat as non-tool
        return False, [], None

    # Encode image as base64 for the API
    image_b64 = base64.b64encode(image_bytes).decode("utf-8")

    prompt = (
        "You see a product image from a hardware / tools / pipes catalog. "
        "The product is typically in color (e.g. metal grey, black, blue, gold) "
        "and placed on a white page background. Treat the outer white area as "
        "paper/background, and everything non-white inside the border as part "
        "of the product. Decide if this is an actual physical product such as "
        "a tool, hardware component, pipe, tube, fitting, hose, coupling, "
        "compressor, pump, or similar item. Ignore pure logos, simple icons, "
        "purely decorative graphics, or almost-empty images. Respond ONLY as "
        "strict JSON with keys: is_hardware_tool (boolean), labels (array of "
        "strings), confidence (number between 0 and 1)."
    )

    try:
        # This uses the Responses API style; adjust if your installed
        # openai client uses a different interface.
        response = client.responses.create(
            model="gpt-4o",
            input=[
                {
                    "role": "user",
                    "content": [
                        {"type": "input_text", "text": prompt},
                        {
                            "type": "input_image",
                            "image": {"format": "webp", "data": image_b64},
                        },
                    ],
                }
            ],
        )

        # Extract the first text output
        text_outputs = []
        for out in getattr(response, "output", []) or []:
            for c in getattr(out, "content", []) or []:
                if getattr(c, "type", None) == "output_text":
                    text_outputs.append(getattr(c, "text", ""))

        if not text_outputs:
            return False, [], None

        raw = text_outputs[0]
        data = json.loads(raw)

        is_tool = bool(data.get("is_hardware_tool", False))
        labels_val = data.get("labels")
        if isinstance(labels_val, list):
            labels = [str(x) for x in labels_val]
        elif isinstance(labels_val, str):
            labels = [labels_val]
        else:
            labels = []

        conf = data.get("confidence")
        try:
            confidence = float(conf) if conf is not None else None
        except (TypeError, ValueError):
            confidence = None

        return is_tool, labels, confidence

    except Exception:
        # On any API or parsing error, fall back to non-tool classification
        return False, [], None


def enrich_json_with_image_labels(data: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Enrich each product's images with hardware-tool classifications.

    This function mutates the product entries in-place and also returns
    the list for convenience.
    """
    for item in data:
        images = item.get("images")
        if not images:
            continue

        any_tool_image = False

        for img in images:
            img_path_str = img.get("image_path")
            if not img_path_str:
                continue

            img_path = Path(img_path_str)
            if not img_path.is_absolute():
                img_path = PROJECT_ROOT / img_path

            if not img_path.exists():
                # Skip if the image file cannot be found on disk
                continue

            is_tool, labels, confidence = classify_image_with_gpt(img_path)

            img["is_hardware_tool"] = bool(is_tool)
            if labels:
                img["hardware_tool_labels"] = labels
            if confidence is not None:
                img["hardware_tool_confidence"] = confidence

            if is_tool:
                any_tool_image = True

        # Optional: set a per-SKU flag if it has at least one tool image
        if any_tool_image:
            item["has_hardware_tool_image"] = True

    return data


def build_output_path(base_input_path: Path) -> Path:
    """Construct a new JSON filename derived from the input analysis file.

    Example:
    input:  input_pdfs_analysis_v5.json
    output: input_pdfs_analysis_with_tools_v1.json (or v2, etc.)
    """
    stem = base_input_path.stem  # e.g. "input_pdfs_analysis_v5"
    suffix = base_input_path.suffix  # ".json"

    base_name = f"{stem}_with_tools"
    version = 1
    while True:
        candidate = OUTPUT_DIR / f"{base_name}_v{version}{suffix}"
        if not candidate.exists():
            return candidate
        version += 1


def main() -> None:
    latest = find_latest_analysis_json()
    if latest is None:
        print(f"No *_analysis_v*.json files found in {OUTPUT_DIR}")
        return

    print(f"Using input analysis JSON: {latest}")

    try:
        with latest.open("r", encoding="utf-8") as f:
            data: List[Dict[str, Any]] = json.load(f)
    except Exception as e:
        print(f"Error reading JSON from {latest}: {e}")
        return

    print(f"Loaded {len(data)} items. Starting image classification...")

    enriched = enrich_json_with_image_labels(data)

    out_path = build_output_path(latest)
    print(f"Writing enriched JSON with hardware-tool labels to: {out_path}")

    try:
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        with out_path.open("w", encoding="utf-8") as f:
            json.dump(enriched, f, ensure_ascii=False, indent=4)
        print("Done.")
    except Exception as e:
        print(f"Error writing enriched JSON: {e}")


if __name__ == "__main__":
    main()
